.TH npass 1 "19 February 2014" "Version 0.1"
.SH NAME
npass - A simple NCurses Interface for Pass
.SH SYNOPSIS
npass
.B [OPTIONS]
.PP
.SH DESCRIPTION
Npass is a simple Ncurses interface for Pass - The Standard Unix Password Manager.
Npass makes the user able to search for his passwords in a faster way.
Npass requires Pass to work.
.SH OPTIONS
.B -c
or
.B --clip
Copy the first line of the password field to the clipboard. The clipboard will be erased in 45 Seconds
.SH AUTHOR
Penazzo Daniele (aka Penaz) (author, current maintainer)
.SH SEE ALSO
pass (1)
