.TH npass 1 "15 April 2014" "Version 0.2"
.SH NAME
npass - A simple NCurses Interface for Pass
.SH SYNOPSIS
npass
.B [OPTIONS]
.PP
.SH DESCRIPTION
Npass is a simple Ncurses interface for Pass - The Standard Unix Password Manager.
Npass makes the user able to search for his passwords in a faster way.
Npass requires Pass to work.
.SH OPTIONS
[
.B -c
,
.B --clip
,
.B --copy
]
Copy the first line of the password field to the clipboard. The clipboard will be erased in 45 Seconds
.PP
[
.B -d
,
.B --delete
]
Delete the selected password when pressing enter.
.PP
[
.B -e
,
.B --edit
]
Edit the selected password when pressing Enter.
.PP
[
.B -h
,
.B --help
]
Show a little help message.
.PP
.SH KEYS
.B Up/Down Arrow
Highlight previous/next password.
.PP
.B Left/Right Arrow
Change mode (Display, Copy, Edit, Delete).
.PP
.B Enter
Execute the current action on the selected password.
.PP
.B [A-z], [0-9] and some symbols
Search for password
.PP
.B Escape (ESC)
Exit npass.
.PP
.SH AUTHOR
Penazzo Daniele (aka Penaz) (author, current maintainer)
.SH SEE ALSO
pass (1)
